version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: restaurant_postgres
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant123
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: restaurant_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: restaurant_user
      SPRING_DATASOURCE_PASSWORD: restaurant123
    ports:
      - "8080:8080"

volumes:
  postgres_data: