spring.application.name=reservation-system

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=restaurant_user
spring.datasource.password=restaurant123!

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: show SQL
spring.jpa.show-sql=true

# Reservation generator
reservation.generator.count=50

reservation.generator.client-names=Alex,John,Maria,David,Anna,Denis,Aleksander,Hendrik

reservation.generator.open-time=09:00
reservation.generator.close-time=22:00

reservation.generator.days-range=7

reservation.generator.min-duration=1
reservation.generator.max-duration=3