# Number of random reservations generated on application startup
reservation.generator.count=50

# Restaurant working hours
reservation.rules.open-time=10:00
reservation.rules.close-time=22:00

# Allowed reservation window (starting from tomorrow)
reservation.rules.days-ahead=7

# Minimum and maximum reservation duration
reservation.rules.min-duration=PT30M
reservation.rules.max-duration=PT2H

# PT30M	    - 30 minutes
# PT2H	    - 2 hours
# PT1H30M   - 1 hour 30 minutes